/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Administrator;

/**
 *
 * @author zili chen
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idButtonGroup = new javax.swing.ButtonGroup();
        infoPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idTextField1 = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        studentRadioButton = new javax.swing.JRadioButton();
        teacherRadioButton = new javax.swing.JRadioButton();
        adminRadioButton = new javax.swing.JRadioButton();
        deanRadioButton = new javax.swing.JRadioButton();
        insDeanRadioButton = new javax.swing.JRadioButton();
        notePanel = new javax.swing.JPanel();
        littlePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));

        idLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(204, 204, 204));
        idLabel.setText("ID");

        idTextField1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        passwordLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel.setText("Password");

        passwordTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        passwordTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        studentRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(studentRadioButton);
        studentRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        studentRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        studentRadioButton.setText("学生");
        studentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRadioButtonActionPerformed(evt);
            }
        });

        teacherRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(teacherRadioButton);
        teacherRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        teacherRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        teacherRadioButton.setText("任课老师");
        teacherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRadioButtonActionPerformed(evt);
            }
        });

        adminRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(adminRadioButton);
        adminRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        adminRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        adminRadioButton.setText("管理员");

        deanRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(deanRadioButton);
        deanRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        deanRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        deanRadioButton.setText("教务处老师");

        insDeanRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(insDeanRadioButton);
        insDeanRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insDeanRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        insDeanRadioButton.setText("院教务员");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                                .addComponent(adminRadioButton)
                                .addGap(18, 18, 18))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(studentRadioButton)
                                .addGap(32, 32, 32)))
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(deanRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(insDeanRadioButton))
                            .addComponent(teacherRadioButton)))
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(infoPanelLayout.createSequentialGroup()
                            .addComponent(passwordLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(infoPanelLayout.createSequentialGroup()
                            .addComponent(idLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminRadioButton)
                    .addComponent(deanRadioButton)
                    .addComponent(insDeanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherRadioButton)
                    .addComponent(studentRadioButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        notePanel.setBackground(new java.awt.Color(0, 0, 0));
        notePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
        notePanel.setLayout(notePanelLayout);
        notePanelLayout.setHorizontalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        notePanelLayout.setVerticalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        littlePanel.setBackground(new java.awt.Color(0, 0, 0));
        littlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout littlePanelLayout = new javax.swing.GroupLayout(littlePanel);
        littlePanel.setLayout(littlePanelLayout);
        littlePanelLayout.setHorizontalGroup(
            littlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        littlePanelLayout.setVerticalGroup(
            littlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(littlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(littlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void teacherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherRadioButtonActionPerformed

    private void studentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.JRadioButton deanRadioButton;
    private javax.swing.ButtonGroup idButtonGroup;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField1;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JRadioButton insDeanRadioButton;
    private javax.swing.JPanel littlePanel;
    private javax.swing.JPanel notePanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JRadioButton teacherRadioButton;
    // End of variables declaration//GEN-END:variables
}
