/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

/**
 *
 * @author Administrator
 */
public class JWMainPanel extends javax.swing.JPanel {
    private JWmain jWmain;
    private FramePanel framePanel=new FramePanel();
    private ModulePanel modulePanel=new ModulePanel();
    private PlanPanel planPanel=new PlanPanel();
    private ProcessMainPanel processMainPanel=new ProcessMainPanel();
    private SendMsgPanel sendMsgPanel=new SendMsgPanel();
    private SetTimePanel setTimePanel=new SetTimePanel();
    private StaticsPanel staticsPanel=new StaticsPanel();
    /**
     * Creates new form JWMainPanel
     */
    public JWMainPanel() {
        initComponents();
     
    }
    public void setContainer(JWmain jWmain1){
        this.jWmain=jWmain1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jwMainPanel = new javax.swing.JPanel();
        titelPanel = new javax.swing.JPanel();
        peopleLogo = new javax.swing.JLabel();
        nameLogo = new javax.swing.JLabel();
        arrowLogo = new javax.swing.JLabel();
        currentLogo = new javax.swing.JLabel();
        backLogo = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        homeLogo = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        exitLogo = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        frameButton = new javax.swing.JButton();
        staticsButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();
        personButton = new javax.swing.JButton();
        frameLabel = new javax.swing.JLabel();
        planLabel = new javax.swing.JLabel();
        staticsLabel = new javax.swing.JLabel();
        processLabel = new javax.swing.JLabel();
        personLabel = new javax.swing.JLabel();
        notePanel = new javax.swing.JPanel();
        planButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(889, 394));

        jwMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        titelPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        peopleLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        peopleLogo.setText("Logo");

        nameLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLogo.setText("name");

        arrowLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo.setText("->");

        currentLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo.setText("current");

        backLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLogo.setText("Logo");

        backLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLabel.setText("back");

        homeLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLogo.setText("Logo");

        homeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLabel.setText("home");

        exitLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLogo.setText("Logo");

        exitLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLabel.setText("exit");

        javax.swing.GroupLayout titelPanelLayout = new javax.swing.GroupLayout(titelPanel);
        titelPanel.setLayout(titelPanelLayout);
        titelPanelLayout.setHorizontalGroup(
            titelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleLogo)
                .addGap(18, 18, 18)
                .addComponent(nameLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrowLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel)
                .addGap(18, 18, 18)
                .addComponent(homeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel)
                .addGap(18, 18, 18)
                .addComponent(exitLogo)
                .addGap(5, 5, 5)
                .addComponent(exitLabel)
                .addContainerGap())
        );
        titelPanelLayout.setVerticalGroup(
            titelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLogo)
                    .addComponent(nameLogo)
                    .addComponent(arrowLogo)
                    .addComponent(currentLogo)
                    .addComponent(backLogo)
                    .addComponent(backLabel)
                    .addComponent(homeLogo)
                    .addComponent(homeLabel)
                    .addComponent(exitLogo)
                    .addComponent(exitLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        frameButton.setText("frame");
        frameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameButtonActionPerformed(evt);
            }
        });

        staticsButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        staticsButton.setText("statics");
        staticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staticsButtonActionPerformed(evt);
            }
        });

        processButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        processButton.setText("process");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        personButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        personButton.setText("person");
        personButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personButtonActionPerformed(evt);
            }
        });

        frameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        frameLabel.setForeground(new java.awt.Color(240, 240, 240));
        frameLabel.setText("教学框架");

        planLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        planLabel.setForeground(new java.awt.Color(240, 240, 240));
        planLabel.setText("教学计划");

        staticsLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        staticsLabel.setForeground(new java.awt.Color(240, 240, 240));
        staticsLabel.setText("统计数据");

        processLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        processLabel.setForeground(new java.awt.Color(240, 240, 240));
        processLabel.setText("进程管理");

        personLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        personLabel.setForeground(new java.awt.Color(240, 240, 240));
        personLabel.setText("个人信息");

        notePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        notePanel.setToolTipText("");

        javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
        notePanel.setLayout(notePanelLayout);
        notePanelLayout.setHorizontalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        notePanelLayout.setVerticalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        planButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        planButton.setText("plan");
        planButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jwMainPanelLayout = new javax.swing.GroupLayout(jwMainPanel);
        jwMainPanel.setLayout(jwMainPanelLayout);
        jwMainPanelLayout.setHorizontalGroup(
            jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jwMainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jwMainPanelLayout.createSequentialGroup()
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frameButton)
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(frameLabel)))
                        .addGap(42, 42, 42)
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addComponent(planButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(staticsButton))
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(planLabel))
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(staticsLabel)))
                        .addGap(64, 64, 64)
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processLabel)
                            .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personButton)
                            .addComponent(personLabel)))
                    .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(titelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jwMainPanelLayout.setVerticalGroup(
            jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jwMainPanelLayout.createSequentialGroup()
                .addComponent(titelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personLabel)
                    .addComponent(processLabel)
                    .addComponent(frameLabel)
                    .addComponent(planLabel)
                    .addComponent(staticsLabel))
                .addGap(18, 18, 18)
                .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jwMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jwMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void staticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staticsButtonActionPerformed
        // TODO add your handling code here:
        jWmain.remove(this);
        setVisible(false);
        jWmain.add(staticsPanel);
        staticsPanel.setVisible(true);
        jWmain.setVisible(true);
    }//GEN-LAST:event_staticsButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        jWmain.remove(this);
        setVisible(false);
        jWmain.add(processMainPanel);
        processMainPanel.setVisible(true);
        jWmain.repaint();
    }//GEN-LAST:event_processButtonActionPerformed

    private void personButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personButtonActionPerformed
        // TODO add your handling code here:
        jWmain.remove(this);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_personButtonActionPerformed

    private void planButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        jWmain.remove(this);
        jWmain.add(planPanel);
        planPanel.setVisible(true);
    }//GEN-LAST:event_planButtonActionPerformed

    private void frameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        jWmain.remove(this);
        jWmain.add(framePanel);
        framePanel.setVisible(true);
    }//GEN-LAST:event_frameButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrowLogo;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel backLogo;
    private javax.swing.JLabel currentLogo;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLogo;
    private javax.swing.JButton frameButton;
    private javax.swing.JLabel frameLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeLogo;
    private javax.swing.JPanel jwMainPanel;
    private javax.swing.JLabel nameLogo;
    private javax.swing.JPanel notePanel;
    private javax.swing.JLabel peopleLogo;
    private javax.swing.JButton personButton;
    private javax.swing.JLabel personLabel;
    private javax.swing.JButton planButton;
    private javax.swing.JLabel planLabel;
    private javax.swing.JButton processButton;
    private javax.swing.JLabel processLabel;
    private javax.swing.JButton staticsButton;
    private javax.swing.JLabel staticsLabel;
    private javax.swing.JPanel titelPanel;
    // End of variables declaration//GEN-END:variables
}
