/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

/**
 *
 * @author zili chen
 */
public class SendMsgPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendMsgPanel
     */
    public SendMsgPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelPanel1 = new javax.swing.JPanel();
        peopleLogo1 = new javax.swing.JLabel();
        nameLogo1 = new javax.swing.JLabel();
        arrowLogo1 = new javax.swing.JLabel();
        currentLogo1 = new javax.swing.JLabel();
        backLogo1 = new javax.swing.JLabel();
        backLabel1 = new javax.swing.JLabel();
        homeLogo1 = new javax.swing.JLabel();
        homeLabel1 = new javax.swing.JLabel();
        exitLogo1 = new javax.swing.JLabel();
        exitLabel1 = new javax.swing.JLabel();
        sendedPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sendedList = new javax.swing.JList();
        addmsgButton = new javax.swing.JButton();
        msgPanel = new javax.swing.JPanel();
        msgLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        receiverLabel = new javax.swing.JLabel();
        insDeanCheckBox = new javax.swing.JCheckBox();
        studentCheckBox1 = new javax.swing.JCheckBox();
        teacherCheckBox = new javax.swing.JCheckBox();
        sureButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        titelPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titelPanel1.setPreferredSize(new java.awt.Dimension(365, 37));

        peopleLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        peopleLogo1.setText("Logo");

        nameLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLogo1.setText("name");

        arrowLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo1.setText("->");

        currentLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo1.setText("current");

        backLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLogo1.setText("Logo");

        backLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLabel1.setText("back");

        homeLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLogo1.setText("Logo");

        homeLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLabel1.setText("home");

        exitLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLogo1.setText("Logo");

        exitLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLabel1.setText("exit");

        javax.swing.GroupLayout titelPanel1Layout = new javax.swing.GroupLayout(titelPanel1);
        titelPanel1.setLayout(titelPanel1Layout);
        titelPanel1Layout.setHorizontalGroup(
            titelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleLogo1)
                .addGap(18, 18, 18)
                .addComponent(nameLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrowLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(backLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel1)
                .addGap(18, 18, 18)
                .addComponent(homeLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel1)
                .addGap(18, 18, 18)
                .addComponent(exitLogo1)
                .addGap(5, 5, 5)
                .addComponent(exitLabel1)
                .addContainerGap())
        );
        titelPanel1Layout.setVerticalGroup(
            titelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLogo1)
                    .addComponent(nameLogo1)
                    .addComponent(arrowLogo1)
                    .addComponent(currentLogo1)
                    .addComponent(backLogo1)
                    .addComponent(backLabel1)
                    .addComponent(homeLogo1)
                    .addComponent(homeLabel1)
                    .addComponent(exitLogo1)
                    .addComponent(exitLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sendedPanel.setBackground(new java.awt.Color(0, 0, 0));
        sendedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "已发送通知", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        sendedList.setBackground(new java.awt.Color(240, 240, 240));
        sendedList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sendedList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(sendedList);

        addmsgButton.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        addmsgButton.setText("+");

        javax.swing.GroupLayout sendedPanelLayout = new javax.swing.GroupLayout(sendedPanel);
        sendedPanel.setLayout(sendedPanelLayout);
        sendedPanelLayout.setHorizontalGroup(
            sendedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(sendedPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(addmsgButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        sendedPanelLayout.setVerticalGroup(
            sendedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addmsgButton)
                .addGap(12, 12, 12))
        );

        msgPanel.setBackground(new java.awt.Color(0, 0, 0));
        msgPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        msgLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(204, 204, 204));
        msgLabel.setText("内容");

        msgTextArea.setBackground(new java.awt.Color(240, 240, 240));
        msgTextArea.setColumns(20);
        msgTextArea.setRows(5);
        msgTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane2.setViewportView(msgTextArea);

        receiverLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        receiverLabel.setForeground(new java.awt.Color(204, 204, 204));
        receiverLabel.setText("通知对象");

        insDeanCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        insDeanCheckBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insDeanCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        insDeanCheckBox.setText("院教务员");

        studentCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        studentCheckBox1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        studentCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        studentCheckBox1.setText("学生");

        teacherCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        teacherCheckBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        teacherCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        teacherCheckBox.setText("任课老师");

        sureButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sureButton.setText("确认");

        cancelButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cancelButton.setText("取消");

        javax.swing.GroupLayout msgPanelLayout = new javax.swing.GroupLayout(msgPanel);
        msgPanel.setLayout(msgPanelLayout);
        msgPanelLayout.setHorizontalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(msgPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(sureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(msgPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(msgPanelLayout.createSequentialGroup()
                                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(receiverLabel)
                                    .addGroup(msgPanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(insDeanCheckBox)
                                        .addGap(37, 37, 37)
                                        .addComponent(teacherCheckBox)))
                                .addGap(52, 52, 52)
                                .addComponent(studentCheckBox1))
                            .addGroup(msgPanelLayout.createSequentialGroup()
                                .addComponent(msgLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        msgPanelLayout.setVerticalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(msgPanelLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherCheckBox)
                            .addComponent(studentCheckBox1))
                        .addGap(27, 27, 27)
                        .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sureButton)
                            .addComponent(cancelButton))
                        .addGap(21, 21, 21))
                    .addGroup(msgPanelLayout.createSequentialGroup()
                        .addComponent(receiverLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insDeanCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titelPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(sendedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titelPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmsgButton;
    private javax.swing.JLabel arrowLogo1;
    private javax.swing.JLabel backLabel1;
    private javax.swing.JLabel backLogo1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentLogo1;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JLabel exitLogo1;
    private javax.swing.JLabel homeLabel1;
    private javax.swing.JLabel homeLogo1;
    private javax.swing.JCheckBox insDeanCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JPanel msgPanel;
    private javax.swing.JTextArea msgTextArea;
    private javax.swing.JLabel nameLogo1;
    private javax.swing.JLabel peopleLogo1;
    private javax.swing.JLabel receiverLabel;
    private javax.swing.JList sendedList;
    private javax.swing.JPanel sendedPanel;
    private javax.swing.JCheckBox studentCheckBox1;
    private javax.swing.JButton sureButton;
    private javax.swing.JCheckBox teacherCheckBox;
    private javax.swing.JPanel titelPanel1;
    // End of variables declaration//GEN-END:variables
}
