/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JWTeacher;

/**
 *
 * @author zili chen
 */
public class ProcessMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessMainPanel
     */
    public ProcessMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameButton = new javax.swing.JButton();
        frameLabel = new javax.swing.JLabel();
        planButton = new javax.swing.JButton();
        planLabel = new javax.swing.JLabel();
        titelPanel1 = new javax.swing.JPanel();
        peopleLogo1 = new javax.swing.JLabel();
        nameLogo1 = new javax.swing.JLabel();
        arrowLogo1 = new javax.swing.JLabel();
        currentLogo1 = new javax.swing.JLabel();
        backLogo1 = new javax.swing.JLabel();
        backLabel1 = new javax.swing.JLabel();
        homeLogo1 = new javax.swing.JLabel();
        homeLabel1 = new javax.swing.JLabel();
        exitLogo1 = new javax.swing.JLabel();
        exitLabel1 = new javax.swing.JLabel();
        timeButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        messageButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        frameButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        frameButton.setText("frame");

        frameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        frameLabel.setForeground(new java.awt.Color(240, 240, 240));
        frameLabel.setText("教学框架");

        planButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        planButton.setText("plan");
        planButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planButtonActionPerformed(evt);
            }
        });

        planLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        planLabel.setForeground(new java.awt.Color(240, 240, 240));
        planLabel.setText("教学计划");

        setBackground(new java.awt.Color(0, 0, 0));

        titelPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titelPanel1.setPreferredSize(new java.awt.Dimension(365, 37));

        peopleLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        peopleLogo1.setText("Logo");

        nameLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLogo1.setText("name");

        arrowLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo1.setText("->");

        currentLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo1.setText("current");

        backLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLogo1.setText("Logo");

        backLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLabel1.setText("back");

        homeLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLogo1.setText("Logo");

        homeLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLabel1.setText("home");

        exitLogo1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLogo1.setText("Logo");

        exitLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLabel1.setText("exit");

        javax.swing.GroupLayout titelPanel1Layout = new javax.swing.GroupLayout(titelPanel1);
        titelPanel1.setLayout(titelPanel1Layout);
        titelPanel1Layout.setHorizontalGroup(
            titelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleLogo1)
                .addGap(18, 18, 18)
                .addComponent(nameLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrowLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(backLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel1)
                .addGap(18, 18, 18)
                .addComponent(homeLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel1)
                .addGap(18, 18, 18)
                .addComponent(exitLogo1)
                .addGap(5, 5, 5)
                .addComponent(exitLabel1)
                .addContainerGap())
        );
        titelPanel1Layout.setVerticalGroup(
            titelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLogo1)
                    .addComponent(nameLogo1)
                    .addComponent(arrowLogo1)
                    .addComponent(currentLogo1)
                    .addComponent(backLogo1)
                    .addComponent(backLabel1)
                    .addComponent(homeLogo1)
                    .addComponent(homeLabel1)
                    .addComponent(exitLogo1)
                    .addComponent(exitLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        timeButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        timeButton.setText("time");
        timeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeButtonActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(240, 240, 240));
        timeLabel.setText("时间安排");

        messageButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        messageButton.setText("message");
        messageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(240, 240, 240));
        messageLabel.setText("通知公告");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titelPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(timeLabel)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(messageLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titelPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageLabel)))
                .addGap(0, 198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void planButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planButtonActionPerformed

    private void messageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageButtonActionPerformed

    private void timeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrowLogo1;
    private javax.swing.JLabel backLabel1;
    private javax.swing.JLabel backLogo1;
    private javax.swing.JLabel currentLogo1;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JLabel exitLogo1;
    private javax.swing.JButton frameButton;
    private javax.swing.JLabel frameLabel;
    private javax.swing.JLabel homeLabel1;
    private javax.swing.JLabel homeLogo1;
    private javax.swing.JButton messageButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel nameLogo1;
    private javax.swing.JLabel peopleLogo1;
    private javax.swing.JButton planButton;
    private javax.swing.JLabel planLabel;
    private javax.swing.JButton timeButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel titelPanel1;
    // End of variables declaration//GEN-END:variables
}
